-- DAY 4 : SQL INTERMEDIATE – JOINS
-- Dataset Used: Sakila Database

-- 1. INNER JOIN
-- So Here iam Combining rentals with customer details
SELECT
    r.rental_id,
    r.rental_date,
    c.first_name,
    c.last_name
FROM rental r
INNER JOIN customer c
ON r.customer_id = c.customer_id;


-- 2. LEFT JOIN
-- Find customers who never rented any film
SELECT
    c.customer_id,
    c.first_name,
    c.last_name
FROM customer c
LEFT JOIN rental r
ON c.customer_id = r.customer_id
WHERE r.rental_id IS NULL;

-- 3. Customer-wise Revenue
-- Calculate total payment made by each customer
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    SUM(p.amount) AS total_revenue
FROM payment p
INNER JOIN customer c
ON p.customer_id = c.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_revenue DESC;


-- 4. Category-wise Revenue
-- Calculate revenue generated by each film category
SELECT
    cat.name AS category_name,
    SUM(p.amount) AS category_revenue
FROM payment p
INNER JOIN rental r ON p.rental_id = r.rental_id
INNER JOIN inventory i ON r.inventory_id = i.inventory_id
INNER JOIN film f ON i.film_id = f.film_id
INNER JOIN film_category fc ON f.film_id = fc.film_id
INNER JOIN category cat ON fc.category_id = cat.category_id
GROUP BY cat.name
ORDER BY category_revenue DESC;
